"""Contracts for the sampled-frame scanner runtime.

The legacy :mod:`book_scanner.session` package remains unchanged.  V1 and
later video work should depend on this package instead of extending the
legacy single-threaded loop's implicit contracts.
"""

from .config import (
    CandidatePolicy,
    CorrectionPipeline,
    DeliveryAckLevel,
    DeliveryPolicy,
    ExtractionPipeline,
    GuidancePolicy,
    ScannerPipelineConfig,
    VideoScannerConfig,
)
from .events import GuidanceRequest, VideoEvent, VideoEventType
from .artifacts import (
    ArtifactCollisionError,
    ArtifactCommitError,
    ArtifactStoreError,
    FilesystemArtifactStore,
)
from .candidate import (
    CandidateAnalyzer,
    CandidateObservation,
    CandidateWindow,
    OpenCVCandidateAnalyzer,
    StabilityAssessment,
    StableWindowAssessor,
)
from .engine import FrameEngineDiagnostics, SampledFrameEngine
from .spread_preparer import (
    SeamUVDocPreparerConfig,
    SeamUVDocSpreadPreparer,
    V2_BUNDLE_SCHEMA_VERSION,
)
from .protocols import (
    ArtifactStore,
    ButtonCommand,
    ButtonSource,
    CameraSource,
    CandidateEvaluator,
    Clock,
    FrameSample,
    GuidanceSink,
    ParserClient,
    SpreadPreparer,
    SpreadProcessor,
)
from .types import (
    ArtifactId,
    FrameCandidate,
    FrameId,
    PageArtifactRef,
    PageSide,
    PreparationDecision,
    PreparationState,
    PreparedPageArtifact,
    PreparedSpreadArtifact,
    ProcessingJobId,
    ReadinessDecision,
    ReadinessReason,
    ReadinessState,
    ReasonCategory,
    SpreadArtifactRef,
    SpreadId,
    VIDEO_SCHEMA_VERSION,
    VideoSessionState,
    is_physical_guidance_reason,
)
from .sources import (
    CameraSourceError,
    CameraUnavailableError,
    FrameDecodeError,
    ImageSequenceCameraSource,
    OpenCVCameraSource,
    SystemClock,
    VideoFileCameraSource,
)

__all__ = [
    "ArtifactId",
    "ArtifactCollisionError",
    "ArtifactCommitError",
    "ArtifactStore",
    "ArtifactStoreError",
    "ButtonCommand",
    "ButtonSource",
    "CameraSource",
    "CameraSourceError",
    "CameraUnavailableError",
    "CandidateAnalyzer",
    "CandidateObservation",
    "CandidateEvaluator",
    "CandidatePolicy",
    "CandidateWindow",
    "Clock",
    "CorrectionPipeline",
    "DeliveryAckLevel",
    "DeliveryPolicy",
    "ExtractionPipeline",
    "FrameCandidate",
    "FrameDecodeError",
    "FrameEngineDiagnostics",
    "FrameId",
    "FrameSample",
    "FilesystemArtifactStore",
    "GuidancePolicy",
    "GuidanceRequest",
    "GuidanceSink",
    "ImageSequenceCameraSource",
    "OpenCVCameraSource",
    "OpenCVCandidateAnalyzer",
    "PageArtifactRef",
    "PageSide",
    "ParserClient",
    "PreparationDecision",
    "PreparationState",
    "PreparedPageArtifact",
    "PreparedSpreadArtifact",
    "ProcessingJobId",
    "ReadinessDecision",
    "ReadinessReason",
    "ReadinessState",
    "ReasonCategory",
    "ScannerPipelineConfig",
    "SampledFrameEngine",
    "SeamUVDocPreparerConfig",
    "SeamUVDocSpreadPreparer",
    "StabilityAssessment",
    "StableWindowAssessor",
    "SpreadArtifactRef",
    "SpreadId",
    "SpreadPreparer",
    "SpreadProcessor",
    "SystemClock",
    "VIDEO_SCHEMA_VERSION",
    "V2_BUNDLE_SCHEMA_VERSION",
    "VideoEvent",
    "VideoEventType",
    "VideoScannerConfig",
    "VideoFileCameraSource",
    "VideoSessionState",
    "is_physical_guidance_reason",
]
