"""judge_capture tested two ways:

(a) against synthetic PageGeometry values, to pin down each threshold branch
    in isolation (fast, deterministic, no image I/O).
(b) end-to-end (measure_page -> judge_capture) against the real sample
    photos and their deliberately rotated/shrunk/cropped variants in
    tests/fixtures/, generated by tests/fixtures/generate_fixtures.py.
"""

from __future__ import annotations

import os

import pytest

from book_scanner.capture.judge import JudgeThresholds, judge_capture
from book_scanner.capture.measure import measure_page_file
from book_scanner.capture.types import PageGeometry, RejectReason

FIXTURES_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "fixtures")
REAL_DIR = os.path.join(FIXTURES_DIR, "real")
GENERATED_DIR = os.path.join(FIXTURES_DIR, "generated")

FRAME = (400, 300)


def _geometry(
    angle_deg: float = 0.0,
    area_ratio: float = 0.5,
    corners: tuple[tuple[float, float], ...] | None = None,
) -> PageGeometry:
    if corners is None:
        # a centered rectangle with generous margin from every frame edge
        corners = ((50.0, 50.0), (350.0, 50.0), (350.0, 250.0), (50.0, 250.0))
    return PageGeometry(
        corners=corners,
        center=(200.0, 150.0),
        size=(300.0, 200.0),
        angle_deg=angle_deg,
        area_ratio=area_ratio,
        frame_size=FRAME,
    )


# -- (a) synthetic threshold-branch tests --------------------------------


def test_page_not_found_when_no_geometry():
    verdict = judge_capture(None)
    assert not verdict.allowed
    assert verdict.reason is RejectReason.PAGE_NOT_FOUND


def test_allowed_for_well_placed_axis_aligned_page():
    verdict = judge_capture(_geometry(angle_deg=0.0, area_ratio=0.5))
    assert verdict.allowed
    assert verdict.reason is None


def test_rejects_excessive_in_plane_rotation():
    verdict = judge_capture(_geometry(angle_deg=30.0, area_ratio=0.5))
    assert not verdict.allowed
    assert verdict.reason is RejectReason.ROTATED_TOO_MUCH


def test_rejects_too_small_area_ratio():
    verdict = judge_capture(_geometry(angle_deg=0.0, area_ratio=0.05))
    assert not verdict.allowed
    assert verdict.reason is RejectReason.TOO_SMALL


def test_rejects_too_large_area_ratio():
    verdict = judge_capture(_geometry(angle_deg=0.0, area_ratio=0.99))
    assert not verdict.allowed
    assert verdict.reason is RejectReason.TOO_LARGE


def test_rejects_corner_touching_frame_edge():
    corners = ((0.0, 50.0), (350.0, 50.0), (350.0, 250.0), (50.0, 250.0))
    verdict = judge_capture(_geometry(angle_deg=0.0, area_ratio=0.5, corners=corners))
    assert not verdict.allowed
    assert verdict.reason is RejectReason.OUT_OF_FRAME


def test_thresholds_are_overridable():
    strict = JudgeThresholds(max_skew_deg=1.0)
    verdict = judge_capture(_geometry(angle_deg=5.0, area_ratio=0.5), thresholds=strict)
    assert not verdict.allowed
    assert verdict.reason is RejectReason.ROTATED_TOO_MUCH


# -- (b) end-to-end against real + deliberately-damaged fixtures ---------


def _judge_file(path: str):
    return judge_capture(measure_page_file(path))


@pytest.mark.skipif(not os.path.isdir(GENERATED_DIR), reason="run generate_fixtures.py first")
def test_good_margin_fixture_is_allowed():
    verdict = _judge_file(os.path.join(GENERATED_DIR, "good_margin.jpg"))
    assert verdict.allowed


@pytest.mark.skipif(not os.path.isdir(GENERATED_DIR), reason="run generate_fixtures.py first")
@pytest.mark.parametrize("name", ["rotated_30.jpg", "rotated_60.jpg"])
def test_rotated_fixtures_are_rejected_for_rotation(name):
    verdict = _judge_file(os.path.join(GENERATED_DIR, name))
    assert not verdict.allowed
    assert verdict.reason is RejectReason.ROTATED_TOO_MUCH


@pytest.mark.skipif(not os.path.isdir(GENERATED_DIR), reason="run generate_fixtures.py first")
def test_shrunk_fixture_is_rejected_as_too_small():
    verdict = _judge_file(os.path.join(GENERATED_DIR, "too_small.jpg"))
    assert not verdict.allowed
    assert verdict.reason is RejectReason.TOO_SMALL


def test_uncropped_real_photo_is_rejected_as_out_of_frame():
    # The raw sample photo fills its own frame edge-to-edge (no margin was
    # left when it was taken), so it is naturally, not synthetically, an
    # out-of-frame case for this judgment.
    verdict = _judge_file(os.path.join(REAL_DIR, "20260825_170921.jpg"))
    assert not verdict.allowed
    assert verdict.reason is RejectReason.OUT_OF_FRAME


@pytest.mark.skipif(not os.path.isdir(GENERATED_DIR), reason="run generate_fixtures.py first")
def test_perspective_warp_fixture_runs_without_crashing():
    # Known limitation (see README): minAreaRect on the warped blob's outer
    # contour stays close to axis-aligned with only a modest area drop, so a
    # moderate trapezoid perspective distortion is NOT reliably caught by
    # the current angle/area-ratio checks alone. Documented here rather than
    # asserted as rejected, so this gap stays visible instead of silently
    # passing or being hacked around with an inflated threshold.
    verdict = _judge_file(os.path.join(GENERATED_DIR, "perspective_warp.jpg"))
    assert verdict is not None
