"""Braille output: 6-dot cell encoding, AST/table -> logical buffer
translation, and viewport windowing. See `cell_encoding.py`'s module
docstring for what is verified against the official 2024 규정 document
versus still an explicit `NotImplementedError` stub."""

from document_parser.accessibility.braille.braille_presenter import BraillePresenter
from document_parser.accessibility.braille.cell_encoding import (
    ABSOLUTE_VALUE_CELL,
    BRACE_CLOSE_CELL,
    BRACE_OPEN_CELL,
    BRACKET_CLOSE_CELLS,
    BRACKET_OPEN_CELLS,
    BrailleCell,
    CAPITAL_INDICATOR_CELL,
    CharacterBrailleTranslator,
    COMMA_CELL,
    DIGIT_CELLS,
    DIGIT_INDICATOR_CELL,
    FINAL_CONSONANT_CELLS,
    FRACTION_BAR_CELL,
    FUNCTION_NAME_CELLS,
    GREEK_LETTER_CELLS,
    GROUPING_BRACKET_CLOSE,
    GROUPING_BRACKET_OPEN,
    INITIAL_CONSONANT_CELLS,
    LOG_CELL,
    MATH_OPERATOR_CELLS,
    PAREN_CLOSE_CELL,
    PAREN_OPEN_CELL,
    RADICAL_CELL,
    RADICAL_NTH_CELL,
    RegulationBrailleTranslator,
    ROMAN_LOWER_CELLS,
    SLASH_FRACTION_CELLS,
    SUBSCRIPT_INDICATOR_CELL,
    SUPERSCRIPT_INDICATOR_CELL,
    SYSTEM_BRACKET_CLOSE_CELLS,
    SYSTEM_BRACKET_OPEN_CELLS,
    cell,
)
from document_parser.accessibility.braille.math_translator import (
    braille_scrollable_spans,
    math_focus_item_to_braille,
)
from document_parser.accessibility.braille.table_formatter import table_cell_braille
from document_parser.accessibility.braille.viewport import (
    build_frame,
    cell_to_int,
    clear_frame,
    last_window_offset,
    scroll,
)

__all__ = [
    "ABSOLUTE_VALUE_CELL",
    "BRACE_CLOSE_CELL",
    "BRACE_OPEN_CELL",
    "BRACKET_CLOSE_CELLS",
    "BRACKET_OPEN_CELLS",
    "CAPITAL_INDICATOR_CELL",
    "COMMA_CELL",
    "DIGIT_CELLS",
    "DIGIT_INDICATOR_CELL",
    "FINAL_CONSONANT_CELLS",
    "FRACTION_BAR_CELL",
    "FUNCTION_NAME_CELLS",
    "GREEK_LETTER_CELLS",
    "GROUPING_BRACKET_CLOSE",
    "GROUPING_BRACKET_OPEN",
    "INITIAL_CONSONANT_CELLS",
    "LOG_CELL",
    "MATH_OPERATOR_CELLS",
    "PAREN_CLOSE_CELL",
    "PAREN_OPEN_CELL",
    "RADICAL_CELL",
    "RADICAL_NTH_CELL",
    "ROMAN_LOWER_CELLS",
    "SLASH_FRACTION_CELLS",
    "SUBSCRIPT_INDICATOR_CELL",
    "SUPERSCRIPT_INDICATOR_CELL",
    "SYSTEM_BRACKET_CLOSE_CELLS",
    "SYSTEM_BRACKET_OPEN_CELLS",
    "BrailleCell",
    "BraillePresenter",
    "CharacterBrailleTranslator",
    "RegulationBrailleTranslator",
    "braille_scrollable_spans",
    "build_frame",
    "cell",
    "cell_to_int",
    "clear_frame",
    "last_window_offset",
    "math_focus_item_to_braille",
    "scroll",
    "table_cell_braille",
]
